### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by mmajcica** [microsoft/vsts-nexus#10]
Hello,

I had the same idea as you and I have created the same build task, however, implemented in PowerShell. It is not yet on the marketplace as I was waiting the legal department from SonaType to give me a go to use their logo and name.
As there may not be the need to have two separate plugins, I would like to suggest a couple of things I already have working and I do find handy.
- Support for Nexus v3 API
- Support for GAV parameters being loaded from POM file
- Specific type of service Endpoint
- Multiple file upload

If you are interested in those and in accepting my work, I would try to implement those in TypeScript.

**Comment by jasholl** [comment]
Hi,

Yes, this all sounds great -- completely agree that one plugin would be ideal.  It would definitely be cool if we could include their logo and name.  We certainly will welcome your contributions, and yes please go with the TypeScript implementation so it works on all platforms.

Jason
