### ISSUE TITLE
Nexus url incorrect formatting

### ISSUE THREAD

**Issue by scotgeeknerd** [microsoft/vsts-nexus#12]
Nexus allows custom url formation.
So it's possible to have a url to access nexus with the format http://nexusserver
Using the service endpoint creation (I've logged a separate bug with TFS),
a / will automatically be appended to the service endpoint.
This results in the service endpoint url being http://nexusserver/
The script for the plugin has the following line of code 
var nexusUploadUrl = serverEndpointUrl + '/service/local/artifact/maven/content';
this results in a nexus upload url of
http://nexusserver//service/local/artifact/maven/content
which is an invalid url.

**Comment by jasholl** [comment]
@scotgeeknerd Thanks for reporting this.  I've fixed this with dc1b80cbc938f9f263251fa98189a846dc618578 and have uploaded a new version of the extension to the marketplace (0.1.5).  The update should automatically be applied to your account, and the next time you run a build, the updated task will be automatically downloaded to your build agent.
