### ISSUE TITLE
nexus plugin works only for maven repositories

### ISSUE THREAD

**Issue by scotgeeknerd** [microsoft/vsts-nexus#13]
Nexus supports multiple repository types
Maven, Nuget, OBR, NPM, RubyGems and Site (as of Nexus version 2.12)

Currently this plugin only supports Maven repository uploads.
Can the plugin be altered to allow the build to select a valid upload repository for technologies other than maven?

**Comment by davidstaheli** [comment]
Thanks for the good suggestion, @scotgeeknerd.  We've got plans to expand support for repository types.  We'd also like to provide a Nexus task for downloading.  In the mean time, can you use the built-in NPM, NuGet, etc. tasks?  I realize they won't provide things that are Nexus-specific.  We'll get the Nexus extension improved as soon as we can.

**Comment by davidstaheli** [comment]
I am closing this issue because support for different repository types (Maven, npm, NuGet, Docker, etc.) will be tracked individually.  Also, in the meantime, repository specific tasks can be used (i.e. the npm task).
