### ISSUE TITLE
¿Nexus version 3.0?

### ISSUE THREAD

**Issue by juanluelguerre** [microsoft/vsts-nexus#17]
Hi guys,

Any idea about when we can use this extensions form Nexus v3.x?

Thanks in advance
Regards
Juanlu

**Comment by davidstaheli** [comment]
Hi @juanluelguerre, unfortunately, Nexus 3 does not yet publish a REST API that can be used by this extension.  In the meantime, one workaround is to use the NuGet, npm, or Maven build/release tasks to upload to or download from Nexus.  See #14.  Thank you for asking!
