### ISSUE TITLE
Success if upload fails

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/vsts-nexus#2]
In this code, it appears the task will succeed if the upload fails.  The error handling block should return instead of continuing execution.

```
request.post({ url: nexusUploadUrl, formData: formData }, function optionalCallback(err, httpResponse, body) {
    if (err) {
        tl.setResult(tl.TaskResult.Failed, err);
    }
    tl.debug('Upload successful, server responded with: ' + body);
    tl.setResult(tl.TaskResult.Succeeded, 'Successfully uploaded ' + fileName);
}).auth(username, password, true);
```

**Comment by jasholl** [comment]
setting the result to failed will fail the task; peeking in the code, the process is actually killed when a task fails.  Here's the doc on the setting the result:  "If the result is Failed (1), then execution will halt."
