### ISSUE TITLE
Packaging input should be a drop-down with set options

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/vsts-nexus#3]
The "Packaging" input is a free-text field.  This presents 2 problems:
1. It would be easy for someone to enter an unsupported value
2. Nexus looks to only support set values: pom, jar, ejb, war, ear, rar, par, maven-archetype, or maven-plugin
We should make this field a drop-down with set options to make it less-fragile.

**Comment by jasholl** [comment]
The packaging actually is free form on nexus;  "pom, jar, ejb, war, ear, rar, par, maven-archetype, or maven-plugin" is a list of prepopulated suggestions, but are not required.
