### ISSUE TITLE
The "Extension" field allows unsupported input values

### ISSUE THREAD

**Issue by davidstaheli** [microsoft/vsts-nexus#4]
The "Extension" input field is currently free-text.  It is unclear whether its value should be preceded with a period, such as ".jar" which is the standard format of a file extension.  When preceded with a period, it doesn't match one of the supported Packaging field values, and these fields should correlate.

The TypeScript code should strip any preceding period from the file extension so that it correlates with the expected Packaging field values.

**Comment by jasholl** [comment]
The extension should be free form because that is what nexus supports.
