### ISSUE TITLE
Does this build extension support Nexus Repository Manager OSS 3.0?

### ISSUE THREAD

**Issue by dangmike** [microsoft/vsts-nexus#5]
Does this build extension support uploading to the recently released Nexus Repository Manager OSS 3.0? Sorry couldn't find a way to post a question.

**Comment by davidstaheli** [comment]
Hi Mike,

We haven't yet tested with 3.0 but we'll let you know as soon as we know ourselves.  This build extension uploads to the Nexus REST endpoint `https://server/service/local/artifact/maven/content`, so as long as that endpoint hasn't changed, things should work.

Thanks,
David

**Comment by ypupo2002** [comment]
The extension does not works with nexus 3.0, as 3.x lacks any kind of rest api. This should be available after version 3.1, see this discussion: https://groups.google.com/a/glists.sonatype.com/forum/#!topic/nexus-users/eb7jeXKNgdU

**Comment by jpricket** [comment]
Closing this issue as ypupo2002 seems to have answered it conclusively. If you desire support for older versions of Nexus server, please open an issue describing what you need. We can't promise that we can work with older servers, but we will consider the request.
