### ISSUE TITLE
Need a way to trust the nexus server certificate.

### ISSUE THREAD

**Issue by ypupo2002** [microsoft/vsts-nexus#9]
When the Nexus repository is hosted under https, if the certificate issued to the server is not valid, the request to upload the file will fail. 
In some cases, there is the need to bypass this behavior, for example, if the certificate is a self signed certificate, or the root certificate authority is an Enterprise Root CA.

**Comment by ypupo2002** [comment]
This is fixed in #8, by adding a input to the task that allows to configure if the request should trust the server certificate.

**Comment by davidstaheli** [comment]
Thanks for the contribution, Yunior!  Can you please address the comment on the pull request?

**Comment by ypupo2002** [comment]
Hi David , I just updated the help of the task according to your comment.
